server:
  port: 8080

spring:
  application:
    name: ms-gateway
  cloud:
    gateway:
      routes:
        - id: pedidos-service
          uri: lb://MS-PEDIDOS
          predicates:
            - Path=/api/pedidos/**
            
        - id: pagos-service
          uri: lb://MS-PAGOS
          predicates:
            - Path=/api/pagos/**
            
        - id: envios-service
          uri: lb://MS-ENVIOS
          predicates:
            - Path=/api/envios/**

        - id: inventario-service
          uri: lb://MS-INVENTARIO
          predicates:
            - Path=/api/inventario/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
